apiVersion: v1
kind: Service
metadata:
  name: graf-service
  labels:
    env: testing
    region: IN
spec:
  selector:
    env: testing
    region: IN
  type: NodePort
  ports:
    - nodePort: 31000
      port: 3000
      targetPort: 3000
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: graf-pv-claim
  labels:
    env: testing
    region: IN
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: graf-service
  labels:
    env: testing
    region: IN
spec:
  selector:
    matchLabels:
      env: testing
      region: IN
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        env: testing
        region: IN
    spec:
      containers:
      - image: yash6899/grafana:1
        name: mygraf
        ports:
        - containerPort: 3000
          name: mygraf
        volumeMounts:
        - name: graf-persistent-storage
          mountPath: /usr/share/grafana/data
      volumes:
      - name: graf-persistent-storage
        persistentVolumeClaim:
          claimName: graf-pv-claim
