apiVersion: v1
kind: ConfigMap
metadata: 
  name: prom-config-file
  labels:
    env: testing
    region: IN
data:
  prometheus.yml: |
    global:
      scrape_interval:     15s 
      evaluation_interval: 15s
    alerting:
      alertmanagers:
      - static_configs:
        - targets:
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
      
      