apiVersion: v1
kind: Service
metadata:
  name: prom-service
  labels:
    env: testing
    region: IN
spec:
  selector:
    env: testing
    region: IN
  type: NodePort
  ports:
    - nodePort: 31001
      port: 9090
      targetPort: 9090
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prom-pv-claim
  labels:
    env: testing
    region: IN
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: prom-service
  labels:
    env: testing
    region: IN
spec:
  selector:
    matchLabels:
      env: testing
      region: IN
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        env: testing
        region: IN
    spec:
      containers:
      - image: yash6899/prometheus:1
        name: myprom
        ports:
        - containerPort: 9090
          name: myprom
        volumeMounts:
        - name: prom-persistent-storage
          mountPath: /prometheus-2.19.0.linux-amd64/data
        - name: prom-config-file
          mountPath: /prometheus-2.19.0.linux-amd64/prometheus.yml
          subPath: prometheus.yml
      volumes:
      - name: prom-persistent-storage
        persistentVolumeClaim:
          claimName: prom-pv-claim
      - name: prom-config-file
        configMap:
          name: prom-config-file
          
